### ISSUE TITLE
Seattle, WA - Date: TBD (late spring)

### ISSUE THREAD

**Issue by thagomizer** [gobridge/workshops#24] opened 2016-01-08 18:35 UTC
Organizers: @thagomizer & @sentientmonkey

Venue: TBD (Likely Google Seattle)

Date: TBD

Curriculum: Probably "Building Web Apps with Go"
### Logistic items
- [ ] Has venue and it sits this many people: ___
- [ ] Has sponsor for food and drinks
- [x] Has organizer(s)
- [ ] Has teacher(s)
- [ ] Has date
- [ ] [Course selected](https://github.com/gobridge/workshops/blob/master/available_courses.md#course-descriptions-and-corresponding-levels)
- [ ] Draft of event started on [Bridge Troll](https://www.bridgetroll.org/events)
- [ ] Included in the event description if bikes are allowed inside or not (ask venue)
- [ ] Included in the event description if child care is available or not

(Issue ready :dart: to be labeled as `scheduled` :boom::v::tada::balloon::rocket: after all tasks above are completed:exclamation:)
### A couple weeks before the event
- [ ] Order placed for catering, if applicable
- [ ] Child care arranged for, if applicable
### First steps
- [x] Self-assigned the issue
- [ ] Pinged the person who opened the issue
- [ ] Google Hangout scheduled (if this is a first timer)

Continue taking the actions necessary to bring issue to a `scheduled` status according to our [issue workflow](https://github.com/gobridge/workshops/blob/master/issue_workflow.md).
### After event is labeled as `scheduled`
- [ ] Bridge Troll event made public; added event link to this thread
- [ ] Opened a meetup event to point to the Bridge Troll event (RSVP on meetup should be closed)
- [ ] Added a PR to add event to GoBridge's website (remove past events while at it)
- [ ] First social media announcement's gone out
- [ ] Conducted organizer training
- [ ] Conducted teacher training
- [ ] Assignee added event date -1 week to calendar as reminder
### Presentations
- [ ] [Opening presentation](https://github.com/gobridge/workshop-material/blob/master/organizer-welcome.slide) forked, edited, and ready to present
- [ ] [Closing presentation](https://github.com/gobridge/workshop-material/blob/master/organizer-closing.slide) forked, edited, and ready to present
### Event date -1 week
- [ ] Confirmed venue and date
- [ ] More rounds of announcements on social media. Mention how many spots left

**Comment by timblair** [comment] 2016-01-17 13:52
Hey, @thagomizer / @sentientmonkey.  It's awesome to see this issue open: it'll be great to have GoBridge kickstarted in Seattle!

Since opening the issue, have you made any further progress?  Has the location been confirmed yet?

**Comment by carlisia** [comment] 2016-02-01 01:24
Hi @thagomizer / @sentientmonkey, we can help put the word out if you'd like to seek out someone to offer venue and/or sponsorship for food and other costs. Can we start doing that?

**Comment by timblair** [comment] 2016-02-10 10:36
@thagomizer / @sentientmonkey: is there anything we can do to help move this workshop forward?

**Comment by timblair** [comment] 2016-02-18 08:54
@thagomizer / @sentientmonkey: I'm going to close this issue for now.  Feel free to reopen it when you're ready, and please get in touch if there's anything we can do to move the event forward.  We'd love to have a workshop in Seattle!

**Closed as completed by timblair** 2016-02-18 08:54 UTC
Labels: logistics/needs sponsor, logistics/needs venue, status/contacted, logistics/needs teacher
