### ISSUE TITLE
Los Angeles, CA : Date TBD 2016 : Go Workshop : Location TBD

### ISSUE THREAD

**Issue by marianaiam** [gobridge/workshops#15] opened 2015-10-25 16:31 UTC
Organizers: @marianaiam @zachgersh
Venue: TBD
Date: TBD
Curriculum: TBD
### Logistic items
- [ ] Has venue and it sits this many people: ___
- [ ] Has sponsor for food and drinks
- [x] Has organizer(s)
- [ ] Has teacher(s)
- [ ] Has date
- [ ] [Course selected](https://github.com/gobridge/workshops/blob/master/available_courses.md#course-descriptions-and-corresponding-levels)
- [ ] Draft of event started on [Bridge Troll](https://www.bridgetroll.org/events)
- [ ] Included in the event description if bikes are allowed inside or not (ask venue)
- [ ] Included in the event description if child care is available or not

(Issue ready :dart: to be labeled as `scheduled` :boom::v::tada::balloon::rocket: after all tasks above are completed:exclamation:)
### A couple weeks before the event
- [ ] Order placed for catering, if applicable
- [ ] Child care arranged for, if applicable
### First steps
- [x] Self-assigned the issue
- [x] Pinged the person who opened the issue
- [x] Google Hangout scheduled (if this is a first timer)

Continue taking the actions necessary to bring issue to a `scheduled` status according to our [issue workflow](https://github.com/gobridge/workshops/blob/master/issue_workflow.md).
### After event is labeled as `scheduled`
- [ ] Bridge Troll event made public; added event link to this thread
- [ ] Opened a meetup event to point to the Bridge Troll event (RSVP on meetup should be closed)
- [ ] Added a PR to add event to GoBridge's website (remove past events while at it)
- [ ] First social media announcement's gone out
- [ ] Conducted organizer training
- [ ] Conducted teacher training
- [ ] Assignee added event date -1 week to calendar as reminder
### Presentations
- [ ] [Opening presentation](https://github.com/gobridge/workshop-material/blob/master/organizer-welcome.slide) forked, edited, and ready to present
- [ ] [Closing presentation](https://github.com/gobridge/workshop-material/blob/master/organizer-closing.slide) forked, edited, and ready to present
### Event date -1 week
- [ ] Confirmed venue and date
- [ ] More rounds of announcements on social media. Mention how many spots left

**Comment by carlisia** [comment] 2015-11-05 03:11
Update: I had a hangout with @marianaIAm and @zachgersh today to iron out details.

**Comment by carlisia** [comment] 2015-11-22 14:38
Hi @marianaiam and @zachgersh!

I wanted to check in and see if we have the venue and sponsorship confirmed so we can update the ticket. 

Also, I would like to introduce you to @oscartaracena, he would like to help with the organizing!

**Comment by carlisia** [comment] 2015-11-22 14:40
Also, wanted to check if you thought about which course you would like to give (https://github.com/gobridge/workshops/blob/master/available_courses.md). If the hardcore Go, there is Bill or a couple of other people who could fly in to teach it.

**Comment by carlisia** [comment] 2016-01-16 18:55
Hi @marianaiam, @zachgersh and @oscartaracena, ready to pick up this thread again? I know you are all interested in having this workshop happen in LA and so am I!

**Comment by oscartaracena** [comment] 2016-01-16 18:57
Same here let's get this started... I am so down for this!!!

Oscar

On Saturday, January 16, 2016, Carlisia Campos notifications@github.com
wrote:

> Hi @marianaiam https://github.com/marianaiam, @zachgersh
> https://github.com/zachgersh and @oscartaracena
> https://github.com/oscartaracena, ready to pick up this thread again? I
> know you are all interested in having this workshop happen in LA and so am
> I!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/gobridge/workshops/issues/15#issuecomment-172246319.

## 

Oscar Taracena
oscar.taracena@gmail.com

**Comment by oscartaracena** [comment] 2016-01-21 00:11
any idea or info about the LA workshop?

On Sat, Jan 16, 2016 at 10:57 AM, oscar taracena oscar.taracena@gmail.com
wrote:

> Same here let's get this started... I am so down for this!!!
> 
> Oscar
> 
> On Saturday, January 16, 2016, Carlisia Campos notifications@github.com
> wrote:
> 
> > Hi @marianaiam https://github.com/marianaiam, @zachgersh
> > https://github.com/zachgersh and @oscartaracena
> > https://github.com/oscartaracena, ready to pick up this thread again?
> > I know you are all interested in having this workshop happen in LA and so
> > am I!
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/gobridge/workshops/issues/15#issuecomment-172246319.
> 
> ## 
> 
> Oscar Taracena
> oscar.taracena@gmail.com

## 

Oscar Taracena
oscar.taracena@gmail.com

**Comment by carlisia** [comment] 2016-02-01 01:37
Contacted the organizers via email, waiting for a response.

**Comment by carlisia** [comment] 2016-02-21 19:20
@oscartaracena the original organizers are not going to be available to move this workshop forward atm. Are you able to take the lead on it? Please let me know.

**Comment by oscartaracena** [comment] 2016-02-22 22:49
I would do it, but I have never ever done anything like this before, and would not know were to start. 

Oscar Taracena
oscar.taracena@gmail.com

**Comment by carlisia** [comment] 2016-02-27 16:49
@oscartaracena since you haven't attended one of our workshops and there's no one at the moment to lead one with you, let's wait until we can get you and at least one more person to do it. I think it will be more manageable that way. I'll close this for now and we'll open a new one for LA, hopefully soon!

**Closed as completed by carlisia** 2016-02-27 16:49 UTC
Labels: logistics/needs sponsor, logistics/needs venue, status/contacted, logistics/needs teacher
